book/urls.py
from django.urls import path
from . import views
from flatpages import views as flatpages_view
from django.views.generic.base import RedirectView
from django.urls import reverse_lazy

app_name="book"

urlpatterns = [
	path('', views.redirect_to_index, name='index'),
	path('all', views.book_all, name='book-all'),
	path('tag/<slug>', views.BookTagView.as_view(), name='book-tag'),
	path('author/<slug>', views.BookAuthorView.as_view(), name='book-author'),
	path('search', views.book_search, name='book-search'),
	path('<slug>', views.BookListView.as_view(), name='book'),
	path('<slug:genre>/<slug:book>', views.BookDetailView.as_view(), name='book-detail'),
	path('<pk>', views.redirectshort, name='redirectshort'),
]

book/forms.py
from django import forms

class SearchForm(forms.Form):
	q = forms.CharField(label='Search Book', max_length=100)

book/templates/book/book_detail.html
{% extends "head.html" %}

{% block title %}
<title>moe.ph - {{ book.title }}
</title>
{% endblock %}

{% block meta %}
<meta property="og:url"                content="{{ request.build_absolute_uri }}" />
<meta property="og:type"               content="website" />
<meta property="og:title"              content="moe.ph - {{ book.title }}" />
<meta property="og:description"        content="{{ book.summary | truncatechars:190 }}" />
<meta property="og:image"              content="{{ book.get_first_volume_image.url }}" />

<meta name="moe.ph - {{ book.title }}" content="{{ book.summary | truncatechars:190 }}">

{% endblock %}

{% block content %}

<!--Main-->
<div id="main">

{% if book %}
	<div class="card m-4">
	<div class="card-body">
	<h2 class="card-title">{{ book.title }}</h2>
	<p class="card-text">{{ book.summary }}</p>
	<ul class="list-group list-group-flush">
	<li class="list-group-item">Author: 
		<a href="{% url 'book:book-author' book.author.code %}">{{ book.author.name }}</a> 
	</li>
	<li class="list-group-item">Genre: 
		<a href="{% url 'book:book' book.genre.code %}">{{ book.genre.name }}</a> 
	</li>
	<li class="list-group-item">Tags: 
		{% for tag in book.get_tags %}
			<a href="{% url 'book:book-tag' tag.code %}">{{ tag.name }}</a>, 
		{% endfor %}
	</li>
	</ul>
	</div>
	</div>

{% endif %}

{% if book.volume_set.all %}
<div class="album p-4 bg-light">
<div class="row">

{% for volume in book.volume_set.all %}

	<div class="col-lg-4 col-md-6">
	<div class="card mb-4 box-shadow">
	{% if volume.image %}
	<img src="{{ volume.image.url }}" class="card-img-top">
	{% endif %}
	<div class="card-body">
	{% if volume.alt_title %}
	<h4 class="card-title">{{ volume.alt_title }}</h4>
	{% else %}
	<h4 class="card-title">{{ volume.title }} {{ volume.volume }}</h4>
	{% endif %}
	<h5 class="card-text">Price:
	<small>P{{ volume.price }}</small>
	</h5>
	</div>
	<div class="card-footer text-muted">
	{{ volume.get_availability }}
	</div>
	</div>
	</div>

{% endfor %}
</div>
</div>

<div class="jumbotron text-center">
<h3>Get in touch with us via <a href="https://m.me/be.moe.ph">Messenger</a>!</h3>
<p></p>
</div>

{% endif %}
</div>



{% endblock %}

book/templates/book/book_list.html
{% extends "head.html" %}

{% block content %}

<!--Main-->

<div id="main">

{% if genre_details %}
<div class="jumbotron text-center">
<h1 class="jumbotron-heading">{{ genre_details.name | capfirst }}</h1>
	<p>{{ genre_details.description }}</p>
</div>
{% endif %}


{% if tag_details %}
<div class="jumbotron text-center">
<h1 class="jumbotron-heading">Filter items by Tag: {{ tag_details.name | capfirst }}</h1>
</div>
{% endif %}

{% if all_details %}
<div class="jumbotron text-center">
<h1 class="jumbotron-heading">Browse All Books</h1>
</div>
{% endif %}

{% if author_details %}
<div class="jumbotron text-center">
<h1 class="jumbotron-heading">Filter items by Author: {{ author_details.name }}</h1>
</div>
{% endif %}

{% if book_list %}
<div class="album p-4 bg-light">
<div class="row">

{% for book in book_list %}
<div class="col-lg-2 col-md-4 col-6">
<div class="card mb-2">
{% if book.get_first_volume_image %}
<a href="{% url 'book:book-detail' book.genre.name book.code %}">
<img class="card-img-top" src="{{ book.get_first_volume_image.url }}" alt="{{ book.get_first_volume_image.name }}">
</a>
{% endif %}
<div class="card-body">
<a href="{% url 'book:book-detail' book.genre.name book.code %}">
<h6 class="card-text">{{ book.title }}
<small class="text-muted"> by {{ book.author }}</small>
</h6></a>
</div>

</div>
</div>
{% endfor %}

{% endif %}
</div>
</div>
</div>

{% endblock %}

book/templates/book/book_search.html
{% extends "head.html" %}

{% block content %}

<!--Main-->

<div class="card my-4">
<div class="jumbotron text-center">
<h1 class="display-5">Search Result for "{{ get_form }}"</h1>
<hr class="my-4">
<form class="my-6 my-lg-0" method="get" action="{% url 'book:book-search' %}">
	<input class="form-control mr-sm-2" type="text" name="q" maxlength="100" required id="id_q" placeholder="Search Item Here" value="{{ get_form }}"/>
	<button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
	</form>
</div>	
</div>


{% if search_result %}
<div class="album p-4 bg-light">
<div class="row">
{% for book in search_result %}
		<div class="col-lg-2 col-md-4 col-6">
		<div class="card mb-2 box-shadow">
		{% if book.get_first_volume_image %}
		<a href="{% url 'book:book-detail' book.genre.code book.code %}">
		<img class="card-img-top" src="{{ book.get_first_volume_image.url }}" alt="{{ book.get_first_volume_image.name }}"></a>
		{% endif %}
		<div class="card-body">
		<a href="{% url 'book:book-detail' book.genre.code book.code %}">
		<h6 class="card-text">{{ book.title }}
		<small class="text-muted">{{ book.author.name }}</small>
		</h6></a>
	</div>
</div>
</div>
{% endfor %}
</div>
</div>

{% else %}

<div class="card my-4">
	<div class="jumbotron text-center">
		<h1 class="display-5">No book found for query "{{ get_form }}"</h1>
		<a href="{% url 'index' %}">
		<p>Go back to Home</p></a>
	</div>
</div>

{% endif %}

{% endblock %}